### ISSUE TITLE
TODO for LFortran

### ISSUE THREAD

**Issue by certik** [prefix-dev/shell#129]
In order for LFortran to be able to switch to Shell, we need to fix the following issues.

High priority (no easy workaround):

* [ ] Both `-e` and `-x`: https://github.com/prefix-dev/shell/issues/62
* [ ] Either https://github.com/prefix-dev/shell/issues/126 or https://github.com/prefix-dev/shell/issues/64
* [ ] https://github.com/prefix-dev/shell/issues/3

Medium priority (workaround possible, but ugly):

* [ ] https://github.com/prefix-dev/shell/issues/127
* [ ] https://github.com/prefix-dev/shell/issues/128
