### ISSUE TITLE
TODO for a daily driver on Windows

### ISSUE THREAD

**Issue by certik** [prefix-dev/shell#35]
I set it up in a Terminal as a shell on WIndows. It's already usable as the default shell. Some things I am missing, high to low priority:

High (no workaround):

* [x] https://github.com/prefix-dev/shell/issues/120
* [x] https://github.com/prefix-dev/shell/issues/62
* [x] https://github.com/prefix-dev/shell/issues/94
* [x] #30 
* [x] #33 

Medium (workaround available or not needed, but ugly or very annoying):

* [ ] #36
* [ ] https://github.com/prefix-dev/shell/issues/201
* [x] https://github.com/prefix-dev/shell/issues/87 (this one I miss a lot)
* [x] https://github.com/prefix-dev/shell/issues/99
* [ ] https://github.com/prefix-dev/shell/issues/84
* [ ] https://github.com/prefix-dev/shell/issues/90
* [ ] https://github.com/prefix-dev/shell/issues/58 (pixi works with the shell already and can install vim, but it must be documented)
* [x] https://github.com/prefix-dev/shell/issues/44

Low (workaround available and only slightly annoying):

* [ ] https://github.com/prefix-dev/shell/issues/131
* [x] #95
* [ ] #114
* [x] #32 
* [x] #29 
* [x] https://github.com/prefix-dev/shell/issues/56

**Comment by wolfv** [comment]
For `ll` should we add an `alias` function and add that to the `ShellState`? Should be pretty trivial..
